### ISSUE TITLE
Buildah/Podman relationship

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/buildah.io#14]
I was pinged in IRC the other day and questioned about the Buildah/Podman relationship.  We probably need to write up a blog or point to the [Containers Tools Guide](https://github.com/containers/buildah/tree/master/docs/containertools) in a prominent way on the site.  Ditto Podman.io.

**Comment by rhatdan** [comment]
Yup.  I thing we wrote up a crictl versus podman, which we should add to the podman.io.

https://blog.openshift.com/crictl-vs-podman/

**Comment by rhatdan** [comment]
@TomSweeneyRedHat This is done correct? Can be closed?

**Comment by TomSweeneyRedHat** [comment]
Forgot all about this @rhatdan, yep done and closing.
