### ISSUE TITLE
Blog post sharing request

### ISSUE THREAD

**Issue by Fodoj** [containers/buildah.io#56]
I recently wrote an article on using Buildah with a real ruby on rails application, perhaps it could be useful for someone if you share this link in buildah blog: https://mkdev.me/en/posts/dockerless-part-2-how-to-build-container-image-for-rails-application-without-docker-and-dockerfile

**Comment by rhatdan** [comment]
Thanks @Fodoj Could you open a PR to add it, we have no problem linking to any articles.

**Comment by TomSweeneyRedHat** [comment]
@Fodoj we'd be happy too.  It would be great if you put up a PR yourself, you'll need to add yourself to _config.yml (see the readme.md for details) and then add a "new" post and a "blog" post in the _posts directory.  You can use these as templates for yours.

https://github.com/containers/buildah.io/blob/master/_posts/2019-04-16-cinc.md
https://github.com/containers/buildah.io/blob/master/_posts/2019-04-16-new.md

**Comment by Fodoj** [comment]
Thanks, done https://github.com/containers/buildah.io/pull/57
